# Generated by Django 5.0.1 on 2024-01-13 17:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OverworkApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateField(default=django.utils.timezone.now, verbose_name='申請日')),
                ('is_approved', models.BooleanField(default=False, help_text='', verbose_name='承認ステータス')),
                ('planned_clock_in', models.TimeField(verbose_name='出社時刻')),
                ('planned_clock_out', models.TimeField(verbose_name='退社時刻')),
                ('planned_overwork', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='申請時間')),
                ('reason', models.CharField(blank=True, help_text='', max_length=255, verbose_name='申請理由')),
                ('approved_by', models.ForeignKey(blank=True, help_text='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_by', to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('submitted_by', models.ForeignKey(help_text='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='submitted_by', to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
            ],
        ),
    ]
